/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Stock } from "./Stock";
import { StockCountArgs } from "./StockCountArgs";
import { StockFindManyArgs } from "./StockFindManyArgs";
import { StockFindUniqueArgs } from "./StockFindUniqueArgs";
import { CreateStockArgs } from "./CreateStockArgs";
import { UpdateStockArgs } from "./UpdateStockArgs";
import { DeleteStockArgs } from "./DeleteStockArgs";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { StockService } from "../stock.service";
@graphql.Resolver(() => Stock)
export class StockResolverBase {
  constructor(protected readonly service: StockService) {}

  async _stocksMeta(
    @graphql.Args() args: StockCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Stock])
  async stocks(@graphql.Args() args: StockFindManyArgs): Promise<Stock[]> {
    return this.service.stocks(args);
  }

  @graphql.Query(() => Stock, { nullable: true })
  async stock(
    @graphql.Args() args: StockFindUniqueArgs
  ): Promise<Stock | null> {
    const result = await this.service.stock(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Stock)
  async createStock(@graphql.Args() args: CreateStockArgs): Promise<Stock> {
    return await this.service.createStock({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Stock)
  async updateStock(
    @graphql.Args() args: UpdateStockArgs
  ): Promise<Stock | null> {
    try {
      return await this.service.updateStock({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Stock)
  async deleteStock(
    @graphql.Args() args: DeleteStockArgs
  ): Promise<Stock | null> {
    try {
      return await this.service.deleteStock(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Transaction], { name: "transactions" })
  async findTransactions(
    @graphql.Parent() parent: Stock,
    @graphql.Args() args: TransactionFindManyArgs
  ): Promise<Transaction[]> {
    const results = await this.service.findTransactions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
